import { useState } from 'react';
import { ChangeItem } from '../types';

interface AttentionDigestProps {
  headline?: string;
  items: ChangeItem[];
  watchlistName: string;
}

export function AttentionDigest({ headline, items, watchlistName }: AttentionDigestProps) {
  const [copied, setCopied] = useState(false);

  // Filter active, non-muted items that have notable attention score (> 20)
  const activeAttentionItems = items
    .filter((i) => !i.isMuted && i.attentionScore > 20)
    .sort((a, b) => b.attentionScore - a.attentionScore);

  const displayHeadline =
    headline ||
    (activeAttentionItems.length > 0
      ? `${activeAttentionItems.length} stocks need your attention today, led by ${activeAttentionItems[0].symbol} (${activeAttentionItems[0].priceChange.percent >= 0 ? '+' : ''}${activeAttentionItems[0].priceChange.percent.toFixed(1)}%).`
      : `All ${items.length} stocks are steady since your last visit — no urgent anomalies detected.`);

  const handleCopyDigest = async () => {
    const lines: string[] = [
      `MarketPulse — Today's Attention Digest (${watchlistName})`,
      '',
      activeAttentionItems.length > 0
        ? `${activeAttentionItems.length} stocks need attention.`
        : 'All stocks are behaving normally since your last visit.',
      '',
    ];

    activeAttentionItems.forEach((item, idx) => {
      const sign = item.priceChange.percent >= 0 ? '+' : '';
      lines.push(`${idx + 1}. ${item.symbol} — ${sign}${item.priceChange.percent.toFixed(1)}%`);
      lines.push(`   Attention Score: ${item.attentionScore}`);
      if (item.volumeAnomaly && item.volumeAnomaly.ratio >= 1.8) {
        lines.push(`   ${item.volumeAnomaly.ratio.toFixed(1)}x volume`);
      }
      if (item.momentumStreak && item.momentumStreak.count >= 2) {
        lines.push(`   ${item.momentumStreak.count}-visit momentum streak`);
      }
      if (item.events && item.events.length > 0) {
        lines.push(`   Event: ${item.events[0].headline}`);
      }
      lines.push('');
    });

    lines.push(`Generated by MarketPulse at ${new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`);

    try {
      await navigator.clipboard.writeText(lines.join('\n'));
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // Fallback for clipboard API permissions
      const textarea = document.createElement('textarea');
      textarea.value = lines.join('\n');
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    }
  };

  return (
    <div className="relative overflow-hidden rounded-2xl border border-indigo-100 bg-white p-5 shadow-sm transition hover:shadow-md">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="space-y-1.5 pr-2">
          <div className="flex items-center gap-2">
            <span className="inline-flex items-center gap-1 rounded-md bg-indigo-50 px-2 py-0.5 text-[11px] font-bold uppercase tracking-wider text-indigo-700">
              <span className="h-1.5 w-1.5 rounded-full bg-indigo-600 animate-pulse" />
              Attention Digest
            </span>
            <span className="text-xs text-slate-600 font-medium">Since your last visit</span>
          </div>
          <p className="text-base sm:text-lg font-semibold text-slate-900 leading-snug">
            "{displayHeadline}"
          </p>
        </div>

        <div className="flex items-center shrink-0">
          <button
            onClick={handleCopyDigest}
            className={`inline-flex items-center gap-2 rounded-xl px-3.5 py-2 text-xs font-semibold transition shadow-sm ${
              copied
                ? 'bg-emerald-50 text-emerald-700 border border-emerald-300'
                : 'bg-white text-slate-700 border border-slate-200 hover:bg-slate-50 hover:border-slate-300'
            }`}
            title="Copy formatted summary to clipboard"
          >
            {copied ? (
              <>
                <svg className="h-3.5 w-3.5 text-emerald-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M5 13l4 4L19 7" />
                </svg>
                <span>✓ Digest copied</span>
              </>
            ) : (
              <>
                <svg className="h-3.5 w-3.5 text-slate-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                </svg>
                <span>Copy today's digest</span>
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}
